# Generated by Django 5.0.6 on 2024-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
