# Generated by Django 5.0.6 on 2024-06-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_createuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='fname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='usern',
            new_name='username',
        ),
    ]
