# Generated by Django 5.0.6 on 2024-06-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_rename_fname_createuser_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='fullname',
            new_name='firstname',
        ),
    ]
