# Generated by Django 5.0.6 on 2024-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_rename_fullname_createuser_firstname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createuser',
        ),
    ]
