# Generated by Django 5.0.6 on 2024-06-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createuser',
        ),
    ]
