# Generated by Django 5.0.6 on 2024-06-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0008_delete_createuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empnum', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.departement')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.locations'),
        ),
    ]
