# Generated by Django 5.0.6 on 2024-06-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_sicknotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sickNotes',
        ),
    ]
