# Generated by Django 5.0.6 on 2024-06-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_delete_sicknotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='sickNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('prove', models.FileField(upload_to='')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.employee')),
            ],
        ),
    ]
