# Generated by Django 5.0.6 on 2024-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_sicknotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicknotes',
            name='prove',
            field=models.ImageField(upload_to=''),
        ),
    ]
