# Generated by Django 5.0.6 on 2024-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_alter_sicknotes_prove'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isnew',
            field=models.BooleanField(default=False),
        ),
    ]
