# Generated by Django 5.0.6 on 2024-06-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0016_alter_employee_isnew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sicknotes',
            old_name='prove',
            new_name='proof',
        ),
    ]
